<script>
    require([
            'jquery',
        ], function (
            $
        ) {
            function addSequraListener() {
                if (!$('.grand .price').length) {
                    setTimeout(function () {
                        addSequraListener();
                    }, 1000);

                    return;
                }

                $('.grand .price').on('DOMSubtreeModified', function () {
                    setAmount();
                })

                setAmount();
            };

            function setAmount() {
                let totals = document.getElementsByClassName('grand totals');

                if (!totals) {
                    return;
                }

                let grandTotal = totals[0].getElementsByClassName('price')[0];
                let sequraElements = document.getElementsByClassName('sequra-promotion-widget');

                console.log('price ' + Number(grandTotal.innerText.replace(/[^0-9\.-]+/g, "")));

                [...sequraElements].forEach((el) => {
                    el.setAttribute('data-amount', (Number(grandTotal.innerText.replace(/[^0-9\.-]+/g, "")) * 100));
                });

                Sequra.refreshComponents?.();
            };

            $(document).ready(function () {
                    addSequraListener();
                }
            );
        }
    );
</script>
