<?php
/** @var WidgetInitializer $block */

use Sequra\Core\Block\WidgetInitializer;

$widgetData = $block->getWidgetInitializeData();

if (!empty($widgetData)):
    // phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Sequra_Core/js/widget-initializer": {
                    "scriptUri": "<?= $widgetData['scriptUri']; ?>",
                "thousandSeparator": "<?= $widgetData['thousandSeparator']; ?>",
                "decimalSeparator": "<?= $widgetData['decimalSeparator']; ?>",
                "locale": "<?= $widgetData['locale']; ?>",
                "merchant": "<?= $widgetData['merchant']; ?>",
                "assetKey": "<?= $widgetData['assetKey']; ?>",
                "products": <?= json_encode($widgetData['products'], JSON_THROW_ON_ERROR); ?>
        }
    }
}
    </script>
    <?php
// phpcs:enable
endif;
