<?php
/** @var \Sequra\Core\Block\WidgetInitializer $block */
$widgetData = $block->getWidgetInitializeData();
// TODO: Unescaped output detected
// phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Sequra_Core/js/widget-initializer": {
                "scriptUri": "<?= $widgetData['scriptUri']; ?>",
                "thousandSeparator": "<?= $widgetData['thousandSeparator']; ?>",
                "decimalSeparator": "<?= $widgetData['decimalSeparator']; ?>",
                "locale": "<?= $widgetData['locale']; ?>",
                "merchant": "<?= $widgetData['merchantId']; ?>",
                "assetKey": "<?= $widgetData['assetKey']; ?>",
                "products": <?= json_encode($widgetData['products']); ?>
    }
}
}
</script>
