<?php
/** @var Sequra\Core\Block\Adminhtml\Configuration\Index $block */
// TODO: Unescaped output detected
// phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
?>

<div id="sequra-page">
    <main id="sq-page-wrapper"></main>
    <div class="sq-page-loader sqs--hidden" id="sq-spinner">
        <div class="sq-loader sqt--large">
            <span class="sqp-spinner"></span>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', () => {
        SequraFE.translations = {
            default: <?= $block->getTranslations()['default']; ?>,
            current: <?= $block->getTranslations()['current']; ?>
        };

        SequraFE.adminLanguage = "<?= $block->getAdminLanguage(); ?>";

        SequraFE.utilities.showLoader();

        const onboardingPageConfig = {
            validateConnectionDataUrl: "<?= $block->getControllerUrl('Onboarding', '{storeId}', 'validateConnectionData'); ?>",
            getConnectionDataUrl: "<?= $block->getControllerUrl('Onboarding', '{storeId}', 'getConnectionData'); ?>",
            saveConnectionDataUrl: "<?= $block->getControllerUrl('Onboarding', '{storeId}', 'setConnectionData'); ?>",
            getSellingCountriesUrl: "<?= $block->getControllerUrl('CountrySettings', '{storeId}', 'getSellingCountries'); ?>",
            getCountrySettingsUrl: "<?= $block->getControllerUrl('CountrySettings', '{storeId}', 'getCountrySettings'); ?>",
            saveCountrySettingsUrl: "<?= $block->getControllerUrl('CountrySettings', '{storeId}', 'setCountrySettings'); ?>",
            getWidgetSettingsUrl: "<?= $block->getControllerUrl('WidgetSettings', '{storeId}', 'getWidgetSettings'); ?>",
            saveWidgetSettingsUrl: "<?= $block->getControllerUrl('WidgetSettings', '{storeId}', 'setWidgetSettings'); ?>",
            getPaymentMethodsUrl: "<?= $block->getControllerUrl('PaymentMethods', '{storeId}', 'getPaymentMethods', '{merchantId}'); ?>",
        }

        const pageConfiguration = {
            onboarding: onboardingPageConfig,
            settings: {
                ...onboardingPageConfig,
                getShopCategoriesUrl: "<?= $block->getControllerUrl('GeneralSettings', '{storeId}', 'getShopCategories'); ?>",
                getGeneralSettingsUrl: "<?= $block->getControllerUrl('GeneralSettings', '{storeId}', 'getGeneralSettings'); ?>",
                saveGeneralSettingsUrl: "<?= $block->getControllerUrl('GeneralSettings', '{storeId}', 'setGeneralSettings'); ?>",
                disconnectUrl: "<?= $block->getControllerUrl('Disconnect', '{storeId}', 'disconnect'); ?>"
            },
            payment: {
                getPaymentMethodsUrl: "<?= $block->getControllerUrl('PaymentMethods', '{storeId}', 'getPaymentMethods', '{merchantId}'); ?>",
                getSellingCountriesUrl: "<?= $block->getControllerUrl('CountrySettings', '{storeId}', 'getSellingCountries'); ?>",
                getCountrySettingsUrl: "<?= $block->getControllerUrl('CountrySettings', '{storeId}', 'getCountrySettings'); ?>",
                getConnectionDataUrl: "<?= $block->getControllerUrl('Onboarding', '{storeId}', 'getConnectionData'); ?>",
                validateConnectionDataUrl: "<?= $block->getControllerUrl('Onboarding', '{storeId}', 'validateConnectionData'); ?>"
            }
        };

        SequraFE.state = new SequraFE.StateController({
            storesUrl: "<?= $block->getControllerUrl('Stores', '{storeId}', 'getStores'); ?>",
            currentStoreUrl: "<?= $block->getControllerUrl('Stores', '{storeId}', 'getCurrentStore'); ?>",
            stateUrl: "<?= $block->getControllerUrl('Integration', '{storeId}', 'getState'); ?>",
            versionUrl: "<?= $block->getControllerUrl('Integration', '{storeId}', 'getVersion'); ?>",
            shopNameUrl: "<?= $block->getControllerUrl('Integration', '{storeId}', 'getShopName'); ?>",
            pageConfiguration: pageConfiguration
        });

        SequraFE.pages = {
            onboarding: ['connect','countries', 'widgets'],
            settings: ['general','connection','widget'],
            payment: ['methods']
        }

        SequraFE.isPromotional = !SequraFE.pages.payment || SequraFE.pages.payment.length === 0;

        SequraFE.state.display();
        SequraFE.utilities.hideLoader();
    });
</script>
