<?php
/** @var \Sequra\Core\Block\ExpressCheckout\MiniCart $block */
/** @var \Magento\Framework\Escaper $escaper */

if ($block->isAvailable()):
    ?>
    <div class="sequra-express-checkout sequra-express-checkout--minicart">
        <button type="button" class="action primary sequra-express-checkout-button">
            <?= $escaper->escapeHtml(__('SeQura Express Checkout')); ?>
        </button>
    </div>
    <?php
elseif ($block->showUnavailableMessage()):
    ?>
    <div class="sequra-express-checkout sequra-express-checkout--minicart">
        <span class="sequra-express-checkout-unavailable">
            <?= $escaper->escapeHtml($block->getUnavailableMessage()); ?>
        </span>
    </div>
    <?php
endif;
