<?php
/** @var MiniWidget $block */

use Sequra\Core\Block\MiniWidget;

$availableWidgets = $block->getAvailableMiniWidgets();

if (!empty($availableWidgets)):
    // phpcs:disable Magento2.Security.XssTemplate.FoundUnescaped
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Sequra_Core/js/widget": {
                    "miniWidgets": <?= json_encode($availableWidgets, JSON_THROW_ON_ERROR); ?>
        }
    }
}
    </script>
    <?php
// phpcs:enable
endif;