<?php $div_id = str_replace('.', '', uniqid('sequra_partpayment_teaser_', true));  ?>
<div id="<?php echo $div_id; ?>"></div>
<script>
    if('undefined' === typeof window.SequraWidgetFacade){
        window.SequraWidgetFacade = {};
    }
    if('undefined' === typeof window.SequraWidgetFacade.widgets){
        window.SequraWidgetFacade.widgets = [];
    }
    if('undefined' === typeof window.SequraWidgetFacade.miniWidgets){
        window.SequraWidgetFacade.miniWidgets = [];
    }
    <?php foreach ($block->getAvailableWidgets() as $widget): ?>
    window.SequraWidgetFacade.widgets.push({
       product: "<?php echo $widget['product']; ?>",
       campaign: "<?php echo $widget['campaign'];?>",
       priceSel: "<?php echo addslashes($widget['priceSel']);?>",
       dest: "<?php echo addslashes($widget['dest']?:"#{$div_id}");?>",
       theme: "<?php echo addslashes($widget['theme']);?>",
       reverse: "<?php echo $widget['reverse'];?>"
    });
    <?php endforeach; ?>
</script>