<div id="sequra_partpayment_teaser"></div>
<script type="text/x-magento-init">
    {
        "#sequra_partpayment_teaser": {
            "Sequra_Core/js/widget-js": {
                "css_price_selector": "<?php echo addslashes($block->getData('price_sel')?:"");?>",
                "css_dest_selector": "<?php echo addslashes($block->getData('dest_sel')?:'#sequra_partpayment_teaser');?>",
                "product": "pp3",
                "theme": "<?php echo addslashes($block->getData('theme')?:"");?>",
                "sequra_configuration":{
                    "scriptUri": "<?php echo $block->getScriptUri(); ?>",
                    "thousandSeparator": "<?php echo $block->getThousandsSeparator(); ?>",
                    "decimalSeparator": "<?php echo $block->getDecimalSeparator(); ?>",
                    "locale": "<?php echo $block->getLocale(); ?>",
                    "merchant": "<?php echo $block->getMerchantRef(); ?>",
                    "assetKey": "<?php echo $block->getAssetsKey(); ?>",
                    "products": <?php echo json_encode($block->getProduct()); ?>
                }
            }
        }
    }
</script>